### ISSUE TITLE
global definitions of Database slots like mims_soil_set have incorrect, implicit range of string

### ISSUE THREAD

**Issue by turbomam** [turbomam/mixs-subset-examples-first#77]
## Global

```yaml
  mims_soil_set:
    name: mims_soil_set
    from_schema: https://github.com/turbomam/mixs-subset-examples-first/tree/main/src/mixs_subset_examples_first
```

## Database slot_usage

```yaml
      mims_soil_set:
        name: mims_soil_set
        multivalued: true
        range: MimsSoil
        inlined_as_list: true
```
